[TM-23] Submit Transfers Pledge
SkillsFundingAgency/das-levy-transfer-matching-api pull request #12
Opened 2021-06-07 11:03 UTC by mmiddleton3301

Stores a pledge in the database.

2021-06-09 10:22 UTC, chrisfoster76 requested changes
A few issues/comments/observations.

In addition: we ought to add a FluentValidator for the incoming request object and ensure that it is valid. This type of validation would just be basic "mandatory field", "valid range of values" etc. and needn't include custom error messages (default is fine, since they'd be read only by a developer, not the end user), but not complex "domain invariants" eg. max amount value for example, which is much more involved.

2021-06-09 10:22 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +    [Route("accounts/{EncodedAccountId}/pledges")]
I think `/pledges` should be the root here, and not `/accounts`.

(Also, if we were dealing with accounts, we would want the raw Id and not the encoded one).

2021-06-09 10:22 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +                Pledge = new Pledge()
I think we could do away with this nested object and flatten the command, so it has all the required properties in the root.

2021-06-09 10:22 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Api/Models/PledgeReferenceDto.cs
> +    public class PledgeReferenceDto
I'd rather we just had a `CreatePledgeResponse` or something similar than a dto.

2021-06-09 10:22 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Api/StartupExtensions/AddConfigurationOptionsExtensions.cs
> +            services.Configure<AccountEncoding>(configuration.GetSection("AccountEncoding"));
Shouldn't need encoder/decoder in the api

2021-06-09 10:22 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Api/StartupExtensions/ServiceCollectionExtensions.cs
> +            services.AddSingleton<IHashingService>((provider) =>
As above, shouldn't be needed - and there is a better `EncodingService` anyway

2021-06-09 10:22 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Database/Tables/Pledge.sql
> +    [HideEmployerName]  BIT           NOT NULL,
Why invert the name/value at the db level?

2021-06-09 10:22 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Database/Tables/PledgeLevel.sql
> +﻿CREATE TABLE [dbo].[PledgeLevel] (
We need to continue a discussion with Tony about this approach, as I don't think it's as elegant as storing as a flags enum.

2021-06-09 10:22 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/CreatePledge/CreatePledgeHandler.cs
> +            await _pledgesDataRepository.Add(pledge);
Is a repository necessary?

2021-06-09 10:22 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Data/Models/Pledge.cs
> +        public decimal Amount { get; set; }
We might have got this wrong elsewhere, but I believe Pledge Amounts are Integer values only.

2021-06-09 10:22 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +            return new AcceptedResult(
I'm not convinced this is the appropriate status code, is it? 201 `Created` would be better? We could still set the location header in this case (we could even echo-out the entire object created in the response body, but perhaps overkill?)

2021-06-09 10:54 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +    [Route("accounts/{EncodedAccountId}/pledges")]
Pending confirmation that this should be changed in both inner and outer API projects, given @abroodie asked for this URL structure when initially implementing work on Friday.

2021-06-09 11:10 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +                Pledge = new Pledge()
Changed.

2021-06-09 11:11 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/StartupExtensions/AddConfigurationOptionsExtensions.cs
> +            services.Configure<AccountEncoding>(configuration.GetSection("AccountEncoding"));
Pending confirmation as to where account encoding should take place (e.g. inner/outer API).

2021-06-09 11:16 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Models/PledgeReferenceDto.cs
> +    public class PledgeReferenceDto
Changed.

2021-06-09 11:17 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/StartupExtensions/ServiceCollectionExtensions.cs
> +            services.AddSingleton<IHashingService>((provider) =>
As above, pending confirmation on where encoding should take place. Could you please let me know where this alternative `EncodingService` is please?

2021-06-09 11:19 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Database/Tables/Pledge.sql
> +    [HideEmployerName]  BIT           NOT NULL,
I was using a script provided to me by @abroodie. I can change this if required?

2021-06-09 11:19 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Database/Tables/PledgeLevel.sql
> +﻿CREATE TABLE [dbo].[PledgeLevel] (
This is fine - I was using a script provided to myself. Please let me know how you'd like it changed. 🙂

2021-06-09 11:20 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/CreatePledge/CreatePledgeHandler.cs
> +            await _pledgesDataRepository.Add(pledge);
I was following EI as far as a pattern goes. Please can you confirm you're happy for me to remove the repository layer?

2021-06-09 11:21 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Data/Models/Pledge.cs
> +        public decimal Amount { get; set; }
I was following the data-type as provided in the EDM provided to me. Please confirm if you'd like this changed all the way through.

2021-06-09 11:21 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +            return new AcceptedResult(
Created would be more appropriate 🙂 This is a mistake. I'll get it changed.

2021-06-09 11:23 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +            return new AcceptedResult(
Additionally, I'm spitting out the `Id`, rather than the whole thing. I figure it's overkill, as it's (currently) not needed. I can get this changed however? Please confirm what you'd like.

2021-06-09 11:35 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +            return new AcceptedResult(
Updated `AcceptedResult` to `CreatedResult`. I've also reflected these changes in the APIM project.

Awaiting confirmation on whether to the entire created instance as part of the response, or whether just the ID (i.e. a reference) would suffice.

2021-06-09 11:43 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +                Pledge = new Pledge()
Note: this has also been changed in the APIM project to be a flat structure.

2021-06-09 12:42 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Api/StartupExtensions/ServiceCollectionExtensions.cs
> +            services.AddSingleton<IHashingService>((provider) =>
We use it in the web project, so you can see how to wire it up/configure it there

2021-06-09 12:45 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Data/Models/Pledge.cs
> +        public decimal Amount { get; set; }
Yes please; I checked with Sam and it should be a whole number

2021-06-09 12:46 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +            return new AcceptedResult(
Just leave it as the Id; we can always change it later if needs be (probably never will be)

2021-06-09 12:47 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Data/Models/Pledge.cs
> +        public decimal Amount { get; set; }
OK, no worries. I'll get this updated throughout all 3 projects.

2021-06-09 12:47 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Database/Tables/Pledge.sql
> +    [HideEmployerName]  BIT           NOT NULL,
Yeah I don't see any reason to invert it; it should be consistent.

2021-06-09 12:48 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Database/Tables/Pledge.sql
> +    [HideEmployerName]  BIT           NOT NULL,
I'll get this updated, and rename the column to reflect the current model.

2021-06-09 12:48 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +            return new AcceptedResult(
OK, thanks. Agreed. Resolving this.

2021-06-09 12:54 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Database/Tables/Pledge.sql
> +    [HideEmployerName]  BIT           NOT NULL,
Changed.

2021-06-09 12:56 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/StartupExtensions/ServiceCollectionExtensions.cs
> +            services.AddSingleton<IHashingService>((provider) =>
I'll hold off changing this for now, until we know where the unpacking should take place.

2021-06-09 12:58 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/CreatePledge/CreatePledgeHandler.cs
> +            await _pledgesDataRepository.Add(pledge);
Received confirmation on Slack from @chrisfoster76 to remove this.

2021-06-09 13:24 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/CreatePledge/CreatePledgeHandler.cs
> +            await _pledgesDataRepository.Add(pledge);
Removed.

2021-06-09 13:33 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Data/Models/Pledge.cs
> +        public decimal Amount { get; set; }
Updated - only needed changes in this project.

2021-06-10 10:42 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +    [Route("accounts/{EncodedAccountId}/pledges")]
Following Slack conversation with @abroodie and @chrisfoster76, the pathing should remain this way, as we're creating a pledge in the context of that account.

2021-06-10 12:54 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/StartupExtensions/AddConfigurationOptionsExtensions.cs
> +            services.Configure<AccountEncoding>(configuration.GetSection("AccountEncoding"));
@abroodie and @chrisfoster76 have indicated that they'd like the account encoding to take place in the outer API, using the following pathing to create a pledge:

* Outer API: **POST** `/accounts/{encodedAccountId}/pledges`
* Inner API: **POST** `/accounts/{accountId}/pledges`

2021-06-10 12:54 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/StartupExtensions/ServiceCollectionExtensions.cs
> +            services.AddSingleton<IHashingService>((provider) =>
To be removed from the API project, and new service to be introcued in Outer API.

2021-06-10 13:21 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/StartupExtensions/AddConfigurationOptionsExtensions.cs
> +            services.Configure<AccountEncoding>(configuration.GetSection("AccountEncoding"));
Updated to use new pathing.

2021-06-10 13:21 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/StartupExtensions/ServiceCollectionExtensions.cs
> +            services.AddSingleton<IHashingService>((provider) =>
Removed.

2021-06-11 08:18 UTC, mmiddleton3301 commented
> If I were to add validation, what would you want validating? The only thing I could think of is to make sure that the enum arrays are non-null: but I'm thinking it might be possible with Swashbuckle to enforce this via schema validation?

It seems this is possible - using `[JsonProperty(Required = Required.DisallowNull)]`.

2021-06-11 08:32 UTC, mmiddleton3301 commented
@chrisfoster76 I ended up making the properties required, and these do not allow null values.

See: https://github.com/SkillsFundingAgency/das-levy-transfer-matching-api/blob/2c8889494974f5ad9bdb502bc43b9d61453ec9d7/src/SFA.DAS.LevyTransferMatching.Api/Models/CreatePledgeRequest.cs

I'll apply this to the Outer API as well, as schema validation is always worth putting in.

If you need any additional (fluent) validation, let me know, and let me know what it is you want to validate.

2021-06-11 08:49 UTC, chrisfoster76 commented
> @chrisfoster76 I ended up making the properties required, and these do not allow null values.
> 
> See: https://github.com/SkillsFundingAgency/das-levy-transfer-matching-api/blob/2c8889494974f5ad9bdb502bc43b9d61453ec9d7/src/SFA.DAS.LevyTransferMatching.Api/Models/CreatePledgeRequest.cs
> 
> I'll apply this to the Outer API as well, as schema validation is always worth putting in.
> 
> If you need any additional (fluent) validation, let me know, and let me know what it is you want to validate.

What about basic validation on the request properties that they are not "empty", i.e. account id can't be zero, etc.

2021-06-11 08:56 UTC, mmiddleton3301 commented
> What about basic validation on the request properties that they are not "empty", i.e. account id can't be zero, etc.

I can get this put in if you like. I'll check on account ID and amount, and make sure they're more than 0.

2021-06-11 10:59 UTC, mmiddleton3301 commented
OK then, so, Schema Validation is handled by Swashbuckle, and now Fluent provides data validation on the model. Responding to `ValidationException`s with a `400/BadRequest`, not gold-plating and leaving room for this to be more 'commonised' down the line.

2021-06-14 08:36 UTC, mmiddleton3301 commented
Authorisation to be handled as part of a different branch, to prevent test environment issues.

Key snippets/files in EI to look at when implementing this:

* https://github.com/SkillsFundingAgency/das-employer-incentives/blob/50980db2ce18bc535287ebee192963ca52f0354c/src/SFA.DAS.EmployerIncentives.Api/Startup.cs#L67-L74
* https://github.com/SkillsFundingAgency/das-employer-incentives/blob/50980db2ce18bc535287ebee192963ca52f0354c/src/SFA.DAS.EmployerIncentives.Api/Extensions/AddAuthenticationExtension.cs

2021-06-14 09:33 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Database/Tables/PledgeLevel.sql
> +﻿CREATE TABLE [dbo].[PledgeLevel] (
@chrisfoster76 and @abroodie have agreed to go with the flags approach.

2021-06-14 12:41 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Database/Tables/PledgeLevel.sql
> +﻿CREATE TABLE [dbo].[PledgeLevel] (
This has been changed.

2021-06-16 09:07 UTC, DannyGB approved these changes

2021-06-29 09:20 UTC, chrisfoster76 approved these changes

2021-06-29 09:25 UTC, merged