TM-29 List available pledges
SkillsFundingAgency/das-levy-transfer-matching-api pull request #13
Opened 2021-06-15 12:57 UTC by ConorTill

Change base to main prior to merge.

2021-06-21 09:27 UTC, chrisfoster76 requested changes
A few observations

2021-06-21 09:27 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Database/Tables/EmployerAccount.sql
> +	[Id] BIGINT NOT NULL PRIMARY KEY,
I'd expect to have a reference to this in the Pledge table definition too, as a foreign key

2021-06-21 09:27 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetPledges/GetPledgesQueryHandler.cs
> +                        DasAccountName = accounts.FirstOrDefault(y => y.Id == x.EmployerAccountId).Name,
If we define a navigation property in Pledge for EmployerAccount, we can change this to a single query performing a join instead of two queries, and improve performance.

2021-06-21 09:27 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Models/Pledge.cs
> +    public class Pledge
It looks like this class is just used for returning the details of the pledge via the GetPledgesResult class. I think it'd be better to move it to be nested _inside_ the GetPledgesResult class, so that there is no temptation to reuse it again elsewhere. This might look like:
```
    public class GetPledgesResult : List<GetPledgesResult.Pledge>
    {
        public GetPledgesResult(IEnumerable<Pledge> collection) : base(collection)
        {
        }

        public  class Pledge
        {
            public int Id { get; set; }
...
```

2021-06-21 11:14 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Database/Tables/EmployerAccount.sql
> +	[Id] BIGINT NOT NULL PRIMARY KEY,
Agreed, fixed.

2021-06-21 12:08 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetPledges/GetPledgesQueryHandler.cs
> +                        DasAccountName = accounts.FirstOrDefault(y => y.Id == x.EmployerAccountId).Name,
Agreed - updated.

2021-06-21 12:09 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Models/Pledge.cs
> +    public class Pledge
Just a point on this - you reviewed this before I had a chance to upload my refactoring of the models - do a pull, and see what you think now.

This leads into what I'm doing on TM-35, where we need to get a single pledge.

If you're still unhappy, I can change.

2021-06-21 12:56 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Models/Pledge.cs
> +    public class Pledge
Following discussion, changed.

2021-06-30 07:23 UTC, chrisfoster76 approved these changes

2021-06-30 07:33 UTC, merged