[TM-35] Option To Apply For Pledge
SkillsFundingAgency/das-levy-transfer-matching-api pull request #15
Opened 2021-06-18 13:09 UTC by mmiddleton3301

Allowing the pulling of a single pledge.

2021-06-30 11:04 UTC, chrisfoster76 requested changes

2021-06-30 11:04 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +            var result = await _mediator.Send(new GetPledgesQuery()
The `GetPledge` controller should be sending a `GetPledgeQuery`, not repurposing another query for another use case.

2021-07-01 12:03 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +            var result = await _mediator.Send(new GetPledgesQuery()
This has been changed.

2021-07-02 10:07 UTC, chrisfoster76 reviewed
Minor changes suggested

2021-07-02 10:07 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetPledge/GetPledgeQueryHandler.cs
> +            var pledge = pledges.SingleOrDefault();
I think you could just to SingleOrDefaultAsync() above and not have to get a list to then get single.

2021-07-02 10:07 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetPledge/GetPledgeQueryHandler.cs
> +            var pledge = pledges.SingleOrDefault();
Oh also if it supports the cancellation token you can pass that in.

2021-07-02 10:07 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetPledge/GetPledgeResult.cs
> +        public object SingleOrDefault()
I'm not sure this should be here.

2021-07-02 11:51 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetPledge/GetPledgeResult.cs
> +        public object SingleOrDefault()
Nope, it shouldn't be - binned it.

2021-07-02 11:52 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetPledge/GetPledgeQueryHandler.cs
> +            var pledge = pledges.SingleOrDefault();
Good spot. Changed.

2021-07-05 14:13 UTC, chrisfoster76 approved these changes

2021-07-16 08:44 UTC, merged