[TM-24] Pledges And Applications
SkillsFundingAgency/das-levy-transfer-matching-api pull request #22
Opened 2021-07-27 13:50 UTC by mmiddleton3301

Updates the list all pledges function to utilise a generic paging wrapper, and provides the addition of an account ID filter.

2021-08-05 10:07 UTC, DannyGB requested changes
I'm getting a failing unit test

2021-08-05 10:07 UTC, DannyGB commented on src/SFA.DAS.LevyTransferMatching.UnitTests/Application/Queries/GetPledges/GetPledgesQueryHandlerTests.cs
> +            var pledges = result.Items.ToArray();
Just a suggestion but I might be tempted to rename this var so that it is more obvious that it is the expected result. It took me a while to figure out when looking at the `Assert.AreEqual`s which was the expected result and which was the actual

2021-08-06 09:09 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.UnitTests/Application/Queries/GetPledges/GetPledgesQueryHandlerTests.cs
> +        public async Task Handle_All_Pledges_Pulled_And_Stitched_Up_With_Accounts()
This is an odd one; it doesn't occur for me. I think it's down to the shared use of the DbContext in the base class. I think I saw a fix for this on one of @chrisfoster76's branches. I'll take another look and see if it helps.

2021-08-06 09:21 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.UnitTests/Application/Queries/GetPledges/GetPledgesQueryHandlerTests.cs
> +            var pledges = result.Items.ToArray();
Good point - updated the variable names to be a little clearer.

2021-08-06 09:29 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.UnitTests/Application/Queries/GetPledges/GetPledgesQueryHandlerTests.cs
> +        public async Task Handle_All_Pledges_Pulled_And_Stitched_Up_With_Accounts()
Pulled in a fix from @chrisfoster76's TM-91 branch:

https://github.com/SkillsFundingAgency/das-levy-transfer-matching-api/blob/TM-91-Auditing/src/SFA.DAS.LevyTransferMatching.UnitTests/DataFixture/LevyTransferMatchingDbContextFixture.cs

The tests seem to complete for me. If this fails in the future, we may need to vend a new DbContext instance for each test in isolation, rather than rely off a base class property.

2021-08-06 10:31 UTC, DannyGB approved these changes

2021-08-20 07:57 UTC, merged