[TM-98] View An Application
SkillsFundingAgency/das-levy-transfer-matching-api pull request #34
Opened 2021-08-12 10:13 UTC by mmiddleton3301

Exposes applications out via the inner API.

2021-09-02 14:14 UTC, chrisfoster76 requested changes
One significant issue that shouldn't take too long to rework.

2021-09-06 11:10 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Data/Repositories/ApplicationRepository.cs
> +        public async Task<Models.Application> Get(int applicationId)
I've removed this method from the `IApplicationRepository`.

2021-09-06 11:11 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetApplication/GetApplicationQueryHandler.cs
> +            var application = await _applicationRepository.Get(request.Id);
I've removed the `IApplicationRepository` from the handler, and inserted the `DbContext` directly. Updated the corresponding unit tests.

2021-09-07 07:56 UTC, chrisfoster76 approved these changes

2021-09-09 12:46 UTC, merged