[TM-140] View Application Details
SkillsFundingAgency/das-levy-transfer-matching-api pull request #44
Opened 2021-09-21 12:18 UTC by mmiddleton3301

Exposes out `IsNamePublic` on the parent pledge when getting an individual application.

2021-09-27 08:40 UTC, chrisfoster76 requested changes
See outer api tech review - this ticket requires a new endpoint.

2021-09-30 09:43 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetApplication/GetApplicationResult.cs
> +        public int PledgeId { get; set; }
Could you also add the Id of the sender and receiver, as we will need this here shortly.

2021-09-30 13:37 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetApplication/GetApplicationResult.cs
> +        public int PledgeId { get; set; }
Done.

2021-10-04 14:57 UTC, chrisfoster76 requested changes

2021-10-04 14:57 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetApplication/GetApplicationQueryHandler.cs
> +                .Where(
I don't find this particularly readable personally. See `GetApplicationsQueryHandler.cs` for an example where a query object is created and parameters conditionally applied to it prior to projection.

2021-10-05 09:25 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/ApplicationsController.cs
> +                result = new OkObjectResult((GetApplicationResponse)queryResult);
Good point. Was having a mad moment I think. Fixed.

2021-10-05 09:26 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/ApplicationsController.cs
> +            IActionResult result = null;
Point taken - changed.

2021-10-05 09:46 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetApplication/GetApplicationQueryHandler.cs
> +                .Where(
Done.

2021-10-14 15:41 UTC, merged