TM-46 Add application wtihdrawal execution path
SkillsFundingAgency/das-levy-transfer-matching-api pull request #63
Opened 2021-11-05 09:49 UTC by ConorTill

2021-11-09 13:18 UTC, mmiddleton3301 requested changes
LGTM, except for the status value chosen - please see comment for more details.

2021-11-09 13:18 UTC, mmiddleton3301 commented on src/SFA.DAS.LevyTransferMatching/Data/Enums/ApplicationStatus.cs
> +        Withdrawn = 5
See my PR regarding this status value for withdrawn:

* https://github.com/SkillsFundingAgency/das-levy-transfer-matching-web/pull/112

2021-11-11 13:14 UTC, chrisfoster76 approved these changes

2021-11-19 16:35 UTC, sscaife approved these changes

2021-11-19 16:44 UTC, merged