Tm 180 export application details csv
SkillsFundingAgency/das-levy-transfer-matching-api pull request #66
Opened 2021-11-09 17:38 UTC by sscaife

2021-11-11 11:25 UTC, chrisfoster76 requested changes

2021-11-11 11:25 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Api/SFA.DAS.LevyTransferMatching.Api.csproj
> +    <NoWin32Manifest>true</NoWin32Manifest>
Did you mean to change this?

2021-11-11 11:25 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Models/Application.cs
> +        public string AboutDetails { get; set; }
Why not `Details`?

2021-11-11 15:15 UTC, sscaife commented on src/SFA.DAS.LevyTransferMatching.Api/SFA.DAS.LevyTransferMatching.Api.csproj
> +    <NoWin32Manifest>true</NoWin32Manifest>
I did not, dunno how I missed that. I have no idea why that was added, or how I missed it with 3 changed files. Sorry about that

2021-11-16 13:28 UTC, chrisfoster76 approved these changes
Minor comments

2021-11-22 11:42 UTC, ConorTill approved these changes

2021-11-23 13:27 UTC, merged