TM27 close a pledge (Inner API)
SkillsFundingAgency/das-levy-transfer-matching-api pull request #77
Opened 2021-12-22 09:23 UTC by jawwadbaig

Close a Pledge inner API changes

2021-12-22 11:35 UTC, chrisfoster76 requested changes

2021-12-22 11:35 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +        [Route("pledges/close/{pledgeId}")]
This is not a RESTful route - it should be `pledges/{pledgeId}/close`

2021-12-22 11:35 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +            var commandResult = await _mediator.Send(new ClosePledgeCommand
The other controllers are pretty inconsistent, but I wonder if we could just throw an exception from within the application layer and allow it to bubble up, rather than having a return type tell us whether it succeeded or not?

2021-12-22 11:35 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommandHandler.cs
> +            if (request == null)
In what scenario would request be null?

2021-12-22 11:35 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommandHandler.cs
> +                return new ClosePledgeResult
I wonder if a cleaner solution would be to create a new custom Exception, say, AggregateNotFoundException, and throw that in the event that the pledge is not found. This would allow the controller to catch this specific exception and return a NotFound response in turn.

We could then try to roll this pattern out for other commands where we haven't been very consistent.

2021-12-22 11:35 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Data/Models/Pledge.cs
> +        {
I'd expect a check here to ensure that the pledge was active - if it's closed already, for example, we could throw an invalidoperation exception to indicate this. It is surely an error to close a closed pledge.

There should be change tracking here, something like this:
```
            StartTrackingSession(UserAction.ClosePledge, userInfo);
            ChangeTrackingSession.TrackUpdate(this);
```
(You'll need to add the `UserAction` enum value).

2021-12-22 11:35 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommand.cs
> +using SFA.DAS.LevyTransferMatching.Data.Enums;
Most of these usings are not required.

2021-12-22 11:35 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommand.cs
> +
Pedantic, but there's a whitespace here.

2021-12-22 11:35 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommandHandler.cs
> +
Pedantic, but there's a whitespace here.

2021-12-22 11:35 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommandHandler.cs
> +
Pedantic, but there's a whitespace here.

2021-12-22 11:35 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeResult.cs
> +﻿using System;
These usings are not required.

2021-12-22 14:07 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommand.cs
> +using SFA.DAS.LevyTransferMatching.Data.Enums;
removed the unnecessary usings.

2021-12-22 14:08 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommand.cs
> +
removed the whitespace

2021-12-22 14:12 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommandHandler.cs
> +            if (request == null)
I have looked at this and it was just an extra if condition. The request will not be null.

2021-12-22 15:22 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommandHandler.cs
> +                return new ClosePledgeResult
A new custom exception AggregateNotFoundException is added. The method throws the AggregateNotFoundException exception when a Pledge ID is not found. Unit test is updated as well for the command handler. And on the controller side we catch this exeption and return NoFound . Controller unit tests are refactored as well.

2021-12-22 15:23 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommandHandler.cs
> +
Its removed now

2021-12-22 15:27 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +        [Route("pledges/close/{pledgeId}")]
This is updated to pledges/{pledgeId}/close

2021-12-22 15:30 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +            var commandResult = await _mediator.Send(new ClosePledgeCommand
This is now updated:  The application layer is now throwing a custom exception and the controller method is catching it and returning the NoFound response.

2021-12-22 15:31 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommandHandler.cs
> +
This whitespace is now removed.

2021-12-22 16:16 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching/Data/Models/Pledge.cs
> +        {
This check has been implemented around the Pledge Status. If the Pledge is already closed, this will throw an InvalidOperationException. Also, the tracking session has been added here with a new UserAction enum.

2021-12-23 09:07 UTC, chrisfoster76 requested changes

2021-12-23 09:07 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommandHandler.cs
> +            pledge.ClosePledge(UserInfo.System);
The `UserInfo` should be obtained from the incoming request (ie, Id and Username should be passed into the api). `UserInfo.System` is for system-originated requests, eg. side-effects of handling messages from this or other systems that are received by the functions app. In this use case, a user clicked a button to cause this state change directly, so we should capture their details.

2021-12-23 09:07 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Data/Models/Pledge.cs
> +            if (Status == PledgeStatus.Active) {
We should implement this check prior to the tracking session being started. There's no need for if/else blocks; just throw the exception if the status is not `Active`, otherwise carry on.

2021-12-23 09:07 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Data/Models/Pledge.cs
> +                throw new InvalidOperationException($"The Pledge Id: {Id} is already closed");
Pedantic, but the error message should not assume that the pledge is closed, since we _could_ have other statuses in future. We could modify the error message to output the current, non-active status.

2021-12-23 12:34 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +                return Ok(commandResult);
I have changed this to Ok().

2021-12-23 13:49 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +                return Ok(commandResult);
Unit test updated.

2021-12-23 14:00 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching/Abstractions/CustomExceptions/AggregateNotFoundException.cs
> +namespace SFA.DAS.LevyTransferMatching.Abstractions.CustomExceptions
That makes sense. Thank you. 
This has been implemented now.

2021-12-23 14:01 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommandHandler.cs
> +                _logger.LogInformation($"The pledge for {request} could not be found.");
Logger is removed.

2021-12-23 15:19 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommandHandler.cs
> +            return new ClosePledgeResult
True, ClosePledgeResult is now removed.

2021-12-23 15:20 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeResult.cs
> +    public class ClosePledgeResult
ClosePledgeResult is now removed

2021-12-23 15:36 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching/Application/Commands/ClosePledge/ClosePledgeCommandHandler.cs
> +            pledge.ClosePledge(UserInfo.System);
Thats a really good point. I have now passed in the UserInfo as part of the incoming request.

2021-12-23 15:45 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching/Data/Models/Pledge.cs
> +            if (Status == PledgeStatus.Active) {
makes sense. I have refactored this section now.

2021-12-23 15:46 UTC, jawwadbaig commented on src/SFA.DAS.LevyTransferMatching/Data/Models/Pledge.cs
> +                throw new InvalidOperationException($"The Pledge Id: {Id} is already closed");
True. I have changed it now.

2022-01-04 09:09 UTC, chrisfoster76 approved these changes

2022-02-07 12:52 UTC, merged