Hr/tm 31 filter pledges by sector
SkillsFundingAgency/das-levy-transfer-matching-api pull request #89
Opened 2022-02-23 13:02 UTC by hasanrq

2022-02-23 16:01 UTC, chrisfoster76 requested changes

2022-02-23 23:05 UTC, hasanrq commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetPledges/GetPledgesQueryHandler.cs
> +                pledgesQuery = pledgesQuery.Where(x => (x.Sectors & request.Sectors) != 0);
[Flags] attribute has been put on ENUM. Also, matching criteria has been modified so that pledges open to ALL sectors will be selected on a filtered output.

2022-03-01 10:34 UTC, chrisfoster76 requested changes

2022-03-01 10:34 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +                Sectors = sectors != null ? (Sector)sectors.Cast<int>().Sum() : 0,
We could move this `.Sum()` line into the query handler, in order to keep it consistent with the other actions - for example, when we create a pledge, this is performed in the handler.

2022-03-01 10:34 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetPledges/GetPledgesQueryHandler.cs
> +                pledgesQuery = pledgesQuery.Where(x => (x.Sectors & request.Sectors) != 0 || x.Sectors == 0);
I can't see a unit test covering this filter

2022-03-01 13:41 UTC, hasanrq commented on src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgesController.cs
> +                Sectors = sectors != null ? (Sector)sectors.Cast<int>().Sum() : 0,
this has been moved to Handler

2022-03-01 13:41 UTC, hasanrq commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetPledges/GetPledgesQueryHandler.cs
> +                pledgesQuery = pledgesQuery.Where(x => (x.Sectors & request.Sectors) != 0 || x.Sectors == 0);
Unit test has been added for filter checking

2022-03-04 08:55 UTC, chrisfoster76 requested changes

2022-03-04 08:55 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching.UnitTests/Application/Queries/GetPledges/GetPledgesQueryHandlerTests.cs
> +        public async Task Handle_Pledges_Are_Filtered_By_Sector()
There are a few issues with this test. Firstly, it is not adequate in terms of covering the various possible values for the Sector filter. For example:

- There is no test to verify that Pledges without Sector criteria are returned no matter the filter value.
- There is no test to verify that Pledges with multiple Sector criteria are returned when any one of those are selected as filter options

There is also an issue I _think_ (happy to be proven wrong) with the actual implementation of the test:

```
var firstPledge = await DbContext.Pledges.FirstAsync();
```

You are selecting the first pledge to use its Sector as the filter value. But since this value will have been generated by autofixture, I believe I am right in saying that as you are taking the first it will always have the same value. Autofixture does not select a "random" value from an enum - instead, it iterates through them, so that the first item generated will have the first enum value, the second will have the next, the third the next, and so on. To put it simply, this means that you only ever test that the Agriculture filter option works.

As a consequence, I can actually change the implementation itself to:


Equality of Sectors in pledge with those in filter (instead of OR):
```
pledgesQuery = pledgesQuery.Where(x => (x.Sectors == (Sector)request.Sectors.Cast<int>().Sum()));
```

Filter only by agriculture!
```
pledgesQuery = pledgesQuery.Where(x => (x.Sectors == Sector.Agriculture));
```

The unit test passes even with these hugely incorrect implementation changes!

This is the natural consequence of writing the unit tests _after_ the implementation. These scenarios and tests should have been thought of before a line of implementation code was written. **We must follow TDD**. If we do not, and unit tests are a mere after-thought, our testing is not thorough - it only gives us _coverage_ instead of meaningful testing of valid use cases.

2022-03-04 08:55 UTC, chrisfoster76 commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetPledges/GetPledgesQueryHandler.cs
> +                pledgesQuery = pledgesQuery.Where(x => (x.Sectors & (Sector)request.Sectors.Cast<int>().Sum()) != 0 || x.Sectors == 0);
For readability, could you please extra this:

```
(Sector)request.Sectors.Cast<int>().Sum()
```

and assign its value to a variable in the previous line.

2022-03-07 14:46 UTC, hasanrq commented on src/SFA.DAS.LevyTransferMatching/Application/Queries/GetPledges/GetPledgesQueryHandler.cs
> +                pledgesQuery = pledgesQuery.Where(x => (x.Sectors & (Sector)request.Sectors.Cast<int>().Sum()) != 0 || x.Sectors == 0);
updated as requested

2022-03-07 15:05 UTC, hasanrq commented on src/SFA.DAS.LevyTransferMatching.UnitTests/Application/Queries/GetPledges/GetPledgesQueryHandlerTests.cs
> +        public async Task Handle_Pledges_Are_Filtered_By_Sector()
I have amended the logic as suggested - now test has collection is different values to test against.

2022-03-08 15:41 UTC, chrisfoster76 approved these changes

2022-03-18 09:44 UTC, merged